# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change

## dependencies that need to be installed beforehand if any
sudo: true
before_install:
  - sudo apt-get install libudunits2-dev libgdal-dev

#addons:
#  apt:
#    packages:
#     - libudunits2-dev

# for codecov
r_packages:
  - covr

# only report coverage after build is successful
after_success:
  - Rscript -e 'covr::codecov()'
